version: '3.4'

networks:
  backend:

services:
  userdb:
    container_name: user-db
    image: mysql:8.0.39-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password@123456
    ports:
      - 8003:3306
    networks:
      - backend

  userservice:
    container_name: user-api
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    networks:
      - backend
    ports:
      - 8004:80
    environment:
      - DB_HOST=userdb
      - DB_NAME=dms_user
      - DB_ROOT_PASSWORD=password@123456

  blogdb:
    container_name: blog-db
    image: mysql:8.0.39-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password@123456
    ports:
      - 8005:3306
    networks:
      - backend

  blogservice:
    container_name: blog-api
    image: ${DOCKER_REGISTRY-}blogservice
    build:
      context: .
      dockerfile: BlogService/Dockerfile
    networks:
      - backend
    ports:
      - 8006:80
    environment:
      - DB_HOST=blogdb
      - DB_NAME=dms_blog
      - DB_ROOT_PASSWORD=password@123456 

  shopdb:
    container_name: shop-db
    image: mysql:8.0.39-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password@123456
    ports:
      - 8007:3306
    networks:
      - backend

  shopservice:
    container_name: shop-api
    image: ${DOCKER_REGISTRY-}shopservice
    build:
      context: .
      dockerfile: ShopService/Dockerfile
    networks:
      - backend
    ports:
      - 8008:80
    environment:
      - DB_HOST=shopdb
      - DB_NAME=dms_shop
      - DB_ROOT_PASSWORD=password@123456  

